### ISSUE TITLE
Missing circuit schematics

### ISSUE THREAD

**Issue by SimoneMarcigaglia** [p4nd4m01um/team17#8]
Cannot find the circuit schematics and pcb design anywhere. 

- Team 3

**Comment by p4nd4m01um** [comment]
you can find it in the folder titled, PCB.

**Comment by p4nd4m01um** [comment]
there are 2 PCB design circuits. one for the motor transistor switch control and the other to connect all the external components out the RPi GPIOs

**Comment by Cao-Jinyu** [comment]
the schematic file is  'sensors.opj '
Please open it in Capture ORCAD PCB designer.
